name: Destroy Backend Env

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment to destroy?"
        required: true
        type: choice
        options:
          - staging

jobs:
  destroy:
    name: Destroy
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    permissions:
      id-token: write
      contents: read

    env:
      TF_VAR_region: ${{ secrets.AWS_REGION }}
      TF_VAR_environment: ${{ github.event.inputs.environment }}
      TF_VAR_app_id: mini-gallery-app
      TF_VAR_route53_zone_name: epic-trip-planner.com
      TF_VAR_api_file_upload_domain_name: ${{ github.event.inputs.environment }}-file-upload-api.epic-trip-planner.com
      TF_VAR_backend_certificate_arn: ${{secrets.BACKEND_CERTIFICATE_ARN}}
      TF_VAR_uploads_bucket_name: mini-gallery-app-uploads
      TF_VAR_secret_store_name: ${{secrets.SECRET_STORE_NAME}}
      TF_VAR_notification_email: ${{secrets.ALERT_EMAIL}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::387836084035:role/githubMiniGalleryAppRole
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Destroy Backend Layer
        working-directory: terraform/live/${{ github.event.inputs.environment }}
        run: |
          terraform init -input=false
          terraform destroy -auto-approve
